"""
Store Intelligence System — Phase 3
events.py

Consumes tracks.json generated by tracking.py and detects when a person
crosses a configurable virtual line corresponding to the CAM3 doorway.
Fires ENTRY and EXIT events, prevents duplicate counting using a hysteresis 
FSM, and exports both events log and an occupancy timeline summary.
"""

from __future__ import annotations

import argparse
import json
import logging
import sys
from collections import defaultdict
from datetime import datetime, timedelta
from pathlib import Path
from typing import Dict, List, Tuple

# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)-8s | %(name)s | %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)
logger = logging.getLogger("store_intelligence.events")


# ---------------------------------------------------------------------------
# Core Event Engine Logic
# ---------------------------------------------------------------------------
class OfflineEventEngine:
    """Consumes tracks records offline and detects virtual line crossings."""

    def __init__(
        self,
        line_y: int = 750,
        line_x1: int = 1400,
        line_x2: int = 1920,
        dead_zone: int = 20,
        cooldown_s: float = 0.5,
        base_time_str: str = "2026-04-10T12:10:00"
    ) -> None:
        self.line_y = line_y
        self.line_x1 = line_x1
        self.line_x2 = line_x2
        self.dead_zone = dead_zone
        self.cooldown_s = cooldown_s
        
        # Parse base time
        try:
            self.base_time = datetime.fromisoformat(base_time_str)
        except ValueError:
            self.base_time = datetime.strptime(base_time_str, "%Y-%m-%dT%H:%M:%S")
            
        logger.info(
            "Event Engine initialized: line_y=%d, line_x=[%d, %d], dead_zone=%dpx, cooldown=%.1fs, base_time=%s",
            line_y, line_x1, line_x2, dead_zone, cooldown_s, base_time_str
        )

    def estimate_fps(self, records: List[dict]) -> float:
        """Estimate the video FPS from frame_ids and timestamps in the records."""
        for r in records:
            f = r["frame_id"]
            t = r["timestamp"]
            if f > 1 and t > 0:
                return round((f - 1) / t, 1)
        return 30.0  # fallback standard FPS

    def process_tracks(self, tracks: List[dict]) -> Tuple[List[dict], dict]:
        """
        Process the raw track list, fire events, calculate statistics, 
        and build the occupancy timeline.
        """
        fps = self.estimate_fps(tracks)
        logger.info("Estimated video FPS: %.1f", fps)

        # 1. Group records by track_id
        tracks_by_id = defaultdict(list)
        for t in tracks:
            tracks_by_id[t["track_id"]].append(t)

        raw_events: List[dict] = []

        # 2. Analyze crossings for each track FSM
        for track_id, records in tracks_by_id.items():
            # Ensure chronological sorting
            records.sort(key=lambda x: x["frame_id"])
            
            first_frame = records[0]["frame_id"]
            last_frame = records[-1]["frame_id"]
            track_duration = round((last_frame - first_frame) / fps, 1)

            last_definite_side = None
            last_event_time = -999.0

            for r in records:
                cx, cy = r["center"]
                frame_id = r["frame_id"]
                timestamp = r["timestamp"]

                # We only evaluate crossings within the horizontal doorway boundaries
                if not (self.line_x1 <= cx <= self.line_x2):
                    continue

                dist = cy - self.line_y

                # Jitter prevention zone
                if abs(dist) <= self.dead_zone:
                    continue

                current_side = "below" if dist > 0 else "above"

                if last_definite_side is None:
                    last_definite_side = current_side
                    continue

                # Definite side transition detected
                if current_side != last_definite_side:
                    event_type = "entry" if (last_definite_side == "above" and current_side == "below") else "exit"

                    # Check cooldown
                    if timestamp - last_event_time >= self.cooldown_s:
                        event_time = self.base_time + timedelta(seconds=timestamp)
                        raw_events.append({
                            "person_id": track_id,
                            "event": event_type,
                            "timestamp": event_time.strftime("%Y-%m-%dT%H:%M:%S"),
                            "frame_id": frame_id,
                            "track_duration": track_duration,
                            # Keep internal raw timestamp for sorting
                            "_raw_timestamp": timestamp,
                            "_event_datetime": event_time
                        })
                        last_event_time = timestamp

                    last_definite_side = current_side

        # 3. Sort all generated events globally in chronological order
        raw_events.sort(key=lambda e: e["_raw_timestamp"])

        # 4. Generate occupancy timeline and verify counts
        total_entries = 0
        total_exits = 0
        occupancy = 0
        peak_occupancy = 0
        occupancy_timeline: List[dict] = []
        final_events: List[dict] = []

        for ev in raw_events:
            if ev["event"] == "entry":
                total_entries += 1
                occupancy += 1
            else:
                total_exits += 1
                occupancy = max(0, occupancy - 1)  # floor to 0

            peak_occupancy = max(peak_occupancy, occupancy)
            
            time_str = ev["_event_datetime"].strftime("%H:%M:%S")
            occupancy_timeline.append({
                "time": time_str,
                "occupancy": occupancy
            })

            # Remove internal fields before final output
            cleaned_ev = {
                "person_id": ev["person_id"],
                "event": ev["event"],
                "timestamp": ev["timestamp"],
                "frame_id": ev["frame_id"],
                "track_duration": ev["track_duration"]
            }
            final_events.append(cleaned_ev)

        summary = {
            "total_entries": total_entries,
            "total_exits": total_exits,
            "current_occupancy": occupancy,
            "peak_occupancy": peak_occupancy,
            "occupancy_timeline": occupancy_timeline
        }

        return final_events, summary


# ---------------------------------------------------------------------------
# CLI Entry Point
# ---------------------------------------------------------------------------
def _build_arg_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="events",
        description="Store Intelligence System — Phase 3: Entry/Exit Event Engine",
        formatter_class=argparse.ArgumentDefaultsHelpFormatter,
    )
    parser.add_argument(
        "--tracks", default="tracks.json",
        help="Path to tracks.json generated by tracking.py"
    )
    parser.add_argument(
        "--events-file", default="events.json",
        help="Path to output events.json file"
    )
    parser.add_argument(
        "--summary-file", default="event_summary.json",
        help="Path to output event_summary.json file"
    )
    parser.add_argument("--line-y", type=int, default=750, help="y-coordinate of the virtual line")
    parser.add_argument("--line-x1", type=int, default=1400, help="left boundary of the virtual line")
    parser.add_argument("--line-x2", type=int, default=1920, help="right boundary of the virtual line")
    parser.add_argument("--dead-zone", type=int, default=20, help="pixels clearance around the line")
    parser.add_argument("--cooldown", type=float, default=0.5, help="seconds between events per person")
    parser.add_argument("--base-time", default="2026-04-10T12:10:00", help="ISO base datetime for video start")
    return parser


def main(argv: list[str] | None = None) -> int:
    parser = _build_arg_parser()
    args = parser.parse_args(argv)

    # Resolve relative paths to absolute paths
    tracks_path = Path(args.tracks).resolve()
    events_path = Path(args.events_file).resolve()
    summary_path = Path(args.summary_file).resolve()

    if not tracks_path.exists():
        logger.error("Input tracks file not found: %s", tracks_path)
        return 1

    logger.info("Reading track records from %s", tracks_path)
    with tracks_path.open("r", encoding="utf-8") as f:
        tracks = json.load(f)

    engine = OfflineEventEngine(
        line_y=args.line_y,
        line_x1=args.line_x1,
        line_x2=args.line_x2,
        dead_zone=args.dead_zone,
        cooldown_s=args.cooldown,
        base_time_str=args.base_time
    )

    events, summary = engine.process_tracks(tracks)

    # Write events log
    events_path.parent.mkdir(parents=True, exist_ok=True)
    events_path.write_text(json.dumps(events, indent=2), encoding="utf-8")
    logger.info("Fired events log exported to %s", events_path)

    # Write event summary
    summary_path.parent.mkdir(parents=True, exist_ok=True)
    summary_path.write_text(json.dumps(summary, indent=2), encoding="utf-8")
    logger.info("Timeline summary exported to %s", summary_path)

    # Output stats to console
    print("\n--- Event Statistics Summary ---")
    print(json.dumps({
        "total_entries": summary["total_entries"],
        "total_exits": summary["total_exits"],
        "current_occupancy": summary["current_occupancy"],
        "peak_occupancy": summary["peak_occupancy"]
    }, indent=2))
    print("--------------------------------\n")

    return 0


if __name__ == "__main__":
    sys.exit(main())
